package com.relative.midas.enums;

public enum EstadoJoyaEnum {
	COTIZADO,
	CUSTODIA,
	PERFECCIONADO,
	EXISTENCIA_LOTE,
	EXISTENCIA_VITRINA,
	RETAZADA_VITRINA,
	RETAZADA_LOTE,
	EXISTENCIA,
	VENDIDA_LOTE,
	VENDIDA_VITRINA,
	DEVUELTA,
	CANCELADA,
	PENDIENTE_HABILITANTE,
	ANULADA

}
