package com.relative.midas.enums;

public enum FileTypeEnum {
	REGISTRO_AVISO_SINIESTRO_MAGAP,
	REGISTRO_AVISO_COSECHA_MAGAP,
	REGISTRO_AVISO_SINIESTRO_LOCAL,
	REGISTRO_AVISO_COSECHA_LOCAL,
	REGISTRO_NEGATIVA,

}
