package com.relative.midas.enums;

public enum ProcesoEnum {
	COMPRA_DIRECTA,
	COMPRA_PLAZO,
	CARGA_HABILITANTES,
	PERFECCIONAMIENTO,
	CANCELAR_CONTRATO,
	RENOVAR_CONTRATO,
	RETASACION_LOTE,
	RETASACION_VITRINA,
	VENTA_LOTE,
	VENTA_VITRINA,
	ENTREGA_JOYA,
	ABONO,
	MOV_ENTRE_CAJA,
	APERTURA_CAJA,
	CIERRE_CAJA,
	COMPRA_PLAZO_ADENDUM,
	RETAZAR_TRASLADAR,
	REVERSO_PERFECCIONAMIENTO,
	ANULACIÓN_CONTRATO
	

}
