package com.relative.midas.enums;

public enum TipoDocumentoEnum {
	COMPRA_PLAZO,
	COMPRA_DIRECTA,
	CONTRATO_CANCELAR,
	CONTRATO_PERFECCIONAR,
	CONTRATO_RENOVAR,
	VENTA_LOTE,
	VENTA_VITRINA,
	DEVOLVER_JOYA,
	COMPRA_PLAZO_ADENDUM,
	COMPROBANTE_ABONO,
	CIERRE_CAJA
}
