--SCRIPT CATALOGO CONDICION PREDIO
INSERT INTO AGRICOLA.CONDICIONPREDIO
(CONDICIONPREDIOID, CONDICIONPREDIOCOD, CONDICIONPREDIODES, CONDICIONPREDIOSTS, CONDICIONPREDIOINSUSR, CONDICIONPREDIOINSTIM, CONDICIONPREDIOUPDUSR, CONDICIONPREDIOUPDTIM, CONDICIONPREDIODELUSR, CONDICIONPREDIODELTIM)
VALUES(CONDICIONPREDIOID.NEXTVAL, 'P', 'PROPIO', 'A', 'ADMIN', TO_DATE('2020/02/05 21:02:44', 'yyyy/mm/dd hh24:mi:ss'), 'ADMIN', TO_DATE('2020/02/05 21:02:44', 'yyyy/mm/dd hh24:mi:ss'), 'ADMIN', TO_DATE('2020/02/05 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));

INSERT INTO AGRICOLA.CONDICIONPREDIO
(CONDICIONPREDIOID, CONDICIONPREDIOCOD, CONDICIONPREDIODES, CONDICIONPREDIOSTS, CONDICIONPREDIOINSUSR, CONDICIONPREDIOINSTIM, CONDICIONPREDIOUPDUSR, CONDICIONPREDIOUPDTIM, CONDICIONPREDIODELUSR, CONDICIONPREDIODELTIM)
VALUES(CONDICIONPREDIOID.NEXTVAL, 'A', 'ALQUILADO-ARRENDADO','A', 'ADMIN', TO_DATE('2020/02/05 21:02:44', 'yyyy/mm/dd hh24:mi:ss'), 'ADMIN', TO_DATE('2020/02/05 21:02:44', 'yyyy/mm/dd hh24:mi:ss'), 'ADMIN', TO_DATE('2020/02/05 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));

INSERT INTO AGRICOLA.CONDICIONPREDIO
(CONDICIONPREDIOID, CONDICIONPREDIOCOD, CONDICIONPREDIODES, CONDICIONPREDIOSTS, CONDICIONPREDIOINSUSR, CONDICIONPREDIOINSTIM, CONDICIONPREDIOUPDUSR, CONDICIONPREDIOUPDTIM, CONDICIONPREDIODELUSR, CONDICIONPREDIODELTIM)
VALUES(CONDICIONPREDIOID.NEXTVAL, 'O', 'OTRO','A', 'ADMIN', TO_DATE('2020/02/05 21:02:44', 'yyyy/mm/dd hh24:mi:ss'), 'ADMIN', TO_DATE('2020/02/05 21:02:44', 'yyyy/mm/dd hh24:mi:ss'), 'ADMIN', TO_DATE('2020/02/05 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));
