--NACIONALIDAD
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('IDN','INDONESIA                                                   ')
,('IMN','ISLA DE MAN                                                 ')
,('IND','INDIA                                                       ')
,('IOT','TERRITORIO BRITANICO DEL OCEANO                             ')
,('IRL','IRLANDA                                                     ')
,('IRN','IRAN                                                        ')
,('IRQ','IRAQ                                                        ')
,('ISL','ISLANDIA                                                    ')
,('ISR','ISRAEL                                                      ')
,('ITA','ITALIA                                                      ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('JAM','JAMAICA                                                     ')
,('JEY','JERSEY                                                      ')
,('JOR','JORDANIA                                                    ')
,('JPN','JAPON                                                       ')
,('KAZ','KAZAJISTAN                                                  ')
,('KEN','KENIA                                                       ')
,('KGZ','KIRGUISTAN                                                  ')
,('KHM','CAMBOYA                                                     ')
,('KIR','KIRIBATI                                                    ')
,('KNA','SAN CRISTOBAL Y NIEVES                                      ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('KOR','COREA DEL SUR                                               ')
,('KWT','KUWAIT                                                      ')
,('LAO','LAOS                                                        ')
,('LBN','LIBANO                                                      ')
,('LBR','LIBERIA                                                     ')
,('LBY','LIBIA                                                       ')
,('LCA','SANTA LUCIA                                                 ')
,('LIE','LIECHTENSTEIN                                               ')
,('LKA','SRI LANKA                                                   ')
,('LSO','LESOTO                                                      ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('LTU','LITUANIA                                                    ')
,('LUX','LUXEMBURGO                                                  ')
,('LVA','LETONIA                                                     ')
,('MAC','MACAO                                                       ')
,('MAR','MARRUECOS                                                   ')
,('MCO','MONACO                                                      ')
,('MDA','MOLDAVIA                                                    ')
,('MDG','MADAGASCAR                                                  ')
,('MDV','MALDIVAS                                                    ')
,('MEX','MEXICO                                                      ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('MHL','ISLAS MARSHALL                                              ')
,('MKD','MACEDONIA                                                   ')
,('MLI','MALI                                                        ')
,('MLT','MALTA                                                       ')
,('MMR','BIRMANIA                                                    ')
,('MNE','MONTENEGRO                                                  ')
,('MNG','MONGOLIA                                                    ')
,('MNP','ISLAS MARIANAS DEL NORTE                                    ')
,('MOZ','MOZAMBIQUE                                                  ')
,('MRT','MAURITANIA                                                  ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('MSR','MONTSERRAT                                                  ')
,('MTQ','MARTINICA                                                   ')
,('MUS','MAURICIO                                                    ')
,('MWI','MALAUI                                                      ')
,('MYS','MALASIA                                                     ')
,('MYT','MAYOTTE                                                     ')
,('NAM','NAMIBIA                                                     ')
,('NCL','NUEVA CALEDONIA                                             ')
,('NER','NIGER                                                       ')
,('NFK','NORFOLK                                                     ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('NGA','NIGERIA                                                     ')
,('NIC','NICARAGUA                                                   ')
,('NIU','NIUE                                                        ')
,('NLD','PAISES BAJOS (HOLANDA)                                      ')
,('NOR','NORUEGA                                                     ')
,('NPL','NEPAL                                                       ')
,('NRU','NAURU                                                       ')
,('NZL','NUEVA ZELANDIA                                              ')
,('OMN','OMAN                                                        ')
,('PAK','PAKISTAN                                                    ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('PAN','PANAMA                                                      ')
,('PCN','ISLAS PITCAIRN                                              ')
,('PER','PERU                                                        ')
,('PHL','FILIPINAS                                                   ')
,('PLW','PALAOS                                                      ')
,('PNG','PAPUA NUEVA GUINEA                                          ')
,('POL','POLONIA                                                     ')
,('PRI','PUERTO RICO                                                 ')
,('PRK','COREA DEL NORTE                                             ')
,('PRT','PORTUGAL                                                    ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('PRY','PARAGUAY                                                    ')
,('PSE','TERRITORIOS PALESTINOS                                      ')
,('PSS','PALESTINA                                                   ')
,('PYF','POLINESIA FRANCESA                                          ')
,('QAT','QATAR                                                       ')
,('REU','REUNION                                                     ')
,('ROU','RUMANIA                                                     ')
,('RUS','RUSIA                                                       ')
,('RWA','RUANDA                                                      ')
,('SAU','ARABIA SAUDITA                                              ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('SDN','SUDAN                                                       ')
,('SEN','SENEGAL                                                     ')
,('SGP','SINGAPUR                                                    ')
,('SGS','ISLAS GEORGIAS DEL SUR Y SANDWICH                           ')
,('SHN','SANTA HELENA                                                ')
,('SJM','SVALBARD Y JAN MAYEN                                        ')
,('SLB','ISLAS SALOMON                                               ')
,('SLE','SIERRA LEONA                                                ')
,('SLV','EL SALVADOR                                                 ')
,('SMR','SAN MARINO                                                  ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('SOM','SOMALIA                                                     ')
,('SPM','SAN PEDRO Y MIQUELON                                        ')
,('SRB','SERBIA                                                      ')
,('STP','SANTO TOME Y PRINCIPE                                       ')
,('SUR','SURINAM                                                     ')
,('SVK','ESLOVAQUIA                                                  ')
,('SVN','ESLOVENIA                                                   ')
,('SWE','SUECIA                                                      ')
,('SWZ','SUAZILANDIA                                                 ')
,('SYC','SEYCHELLES                                                  ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('SYR','SIRIA                                                       ')
,('TCA','ISLAS TURCAS Y CAICOS                                       ')
,('TCD','CHAD                                                        ')
,('TGO','TOGO                                                        ')
,('THA','TAILANDIA                                                   ')
,('TJK','TAYIKISTAN                                                  ')
,('TKL','TOKELAU                                                     ')
,('TKM','TURKMENISTAN                                                ')
,('TLS','TIMOR ORIENTAL                                              ')
,('TON','TONGA                                                       ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('TTO','TRINIDAD Y TOBAGO                                           ')
,('TUN','TUNEZ                                                       ')
,('TUR','TURQUIA                                                     ')
,('TWN','TAIWAN                                                      ')
,('TZA','TANZANIA                                                    ')
,('UGA','UGANDA                                                      ')
,('UKR','UCRANIA                                                     ')
,('UMI','ISLAS ULTRAMARINAS DE ESTADOS                               ')
,('URS','UNION SOVIETICA                                             ')
,('URY','URUGUAY                                                     ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('USA','ESTADOS UNIDOS                                              ')
,('UZB','UZBEKISTAN                                                  ')
,('VAT','CIUDAD DEL VATICANO                                         ')
,('VCT','SAN VICENTE Y LAS GRANADINAS                                ')
,('VEN','VENEZUELA                                                   ')
,('VGB','ISLAS VIRGENES BRITANICAS                                   ')
,('VIR','ISLAS VIRGENES ESTADOUNIDENSES                              ')
,('VNM','VIETNAM                                                     ')
,('VUT','VANUATU                                                     ')
,('WLF','WALLIS Y FUTUNA                                             ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('WSM','SAMOA                                                       ')
,('YEM','YEMEN                                                       ')
,('ZAF','SUDAFRICA                                                   ')
,('ZMB','ZAMBIA                                                      ')
,('ZWE','ZIMBABUE                                                    ')
,('GUY','GUYANA                                                      ')
,('HKG','HONG KONG                                                   ')
,('HMD','ISLAS HEARD Y MCDONALD                                      ')
,('HND','HONDURAS                                                    ')
,('HRV','CROACIA                                                     ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('HTI','HAITI                                                       ')
,('HUN','HUNGRIA                                                     ')
,('ABW','ARUBA                                                       ')
,('AFG','AFGANISTAN                                                  ')
,('AGO','ANGOLA                                                      ')
,('AIA','ANGUILA                                                     ')
,('ALA','ALAND                                                       ')
,('ALB','ALBANIA                                                     ')
,('ANT','ANTILLAS NEERLANDESAS                                       ')
,('ARE','EMIRATOS ARABES UNIDOS                                      ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('ARG','ARGENTINA                                                   ')
,('ARM','ARMENIA                                                     ')
,('ASM','SAMOA AMERICANA                                             ')
,('ATA','ANTARTIDA                                                   ')
,('ATF','TERRITORIOS AUSTRALES FRANCESES                             ')
,('ATG','ANTIGUA Y BARBUDA                                           ')
,('AUS','AUSTRALIA                                                   ')
,('AUT','AUSTRIA                                                     ')
,('AZE','AZERBAIYAN                                                  ')
,('BDI','BURUNDI                                                     ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('BEL','BELGICA                                                     ')
,('BEN','BENIN                                                       ')
,('BFA','BURKINA FASO                                                ')
,('BGD','BANGLADESH                                                  ')
,('BGR','BULGARIA                                                    ')
,('BHR','BAHREIN                                                     ')
,('BHS','BAHAMAS                                                     ')
,('BIH','BOSNIA Y HERZEGOVINA                                        ')
,('BLM','SAN BARTOLOME                                               ')
,('BLR','BIELORRUSIA                                                 ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('BLZ','BELICE                                                      ')
,('BMU','BERMUDAS                                                    ')
,('BOL','BOLIVIA                                                     ')
,('BRA','BRASIL                                                      ')
,('BRB','BARBADOS                                                    ')
,('BRN','BRUNEI                                                      ')
,('BTN','BUTAN                                                       ')
,('BVT','ISLA BOUVET                                                 ')
,('BWA','BOTSUANA                                                    ')
,('CAF','REPUBLICA CENTROAFRICANA                                    ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('CAN','CANADA                                                      ')
,('CCK','ISLAS COCOS                                                 ')
,('CGS','CONGO BRAZZAVILLE                                           ')
,('CHE','SUIZA                                                       ')
,('CHL','CHILE                                                       ')
,('CHN','CHINA                                                       ')
,('CIV','COSTA DE MARFIL                                             ')
,('CMR','CAMERUN                                                     ')
,('COD','REPUBLICA DEMOCRATICA DEL CONGO                             ')
,('COG','REPUBLICA DEL CONGO                                         ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('COK','ISLAS COOK                                                  ')
,('COL','COLOMBIA                                                    ')
,('COM','CAMORAS                                                     ')
,('CPV','CABO VERDE                                                  ')
,('CRI','COSTA RICA                                                  ')
,('CUB','CUBA                                                        ')
,('CXR','ISLA DE NAVIDAD                                             ')
,('CYK','ISLAS CANTON Y ENDERBURY                                    ')
,('CYM','ISLAS CAIMAN                                                ')
,('CYP','CHIPRE                                                      ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('CZE','REPUBLICA CHECA                                             ')
,('DEU','ALEMANIA                                                    ')
,('DJI','YIBUTI                                                      ')
,('DMA','DOMINICA                                                    ')
,('DNK','DINAMARCA                                                   ')
,('DOM','REPUBLICA DOMINICANA                                        ')
,('DZA','ARGELIA                                                     ')
,('ECU','ECUADOR                                                     ')
,('EGY','EGIPTO                                                      ')
,('ERI','ERITREA                                                     ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('ESH','SAHARA OCCIDENTAL                                           ')
,('ESP','ESPAÑA                                                      ')
,('EST','ESTONIA                                                     ')
,('ETH','ETIOPIA                                                     ')
,('EUR','UNION EUROPEA                                               ')
,('FIN','FINLANDIA                                                   ')
,('FJI','FIYI                                                        ')
,('FLK','ISLAS MALVINAS                                              ')
,('FRA','FRANCIA                                                     ')
,('FRO','ISLAS FEROE                                                 ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('FSM','MICRONESIA                                                  ')
,('GAB','GABON                                                       ')
,('GBR','REINO UNIDO (INGLATERRA)                                    ')
,('GEO','GEORGIA                                                     ')
,('GGY','GUERNSEY                                                    ')
,('GHA','GHANA                                                       ')
,('GIB','GIBRALTAR                                                   ')
,('GIN','GUINEA                                                      ')
,('GLP','GUADALUPE                                                   ')
,('GMB','GAMBIA                                                      ')
;
INSERT INTO AGRICOLA.NACIONALIDAD (NACIONALIDADID,NACIONALIDADDES) VALUES 
('GNB','GUINEA-BISSAU                                               ')
,('GNQ','GUINEA ECUATORIAL                                           ')
,('GRC','GRECIA                                                      ')
,('GRD','GRANADA                                                     ')
,('GRL','GROENLANDIA                                                 ')
,('GTM','GUATEMALA                                                   ')
,('GUF','GUAYANA FRANCESA                                            ')
,('GUM','GUAM                                                        ')
;