
--CREACION DE TABLAS TIPO DOCUMENTO Y DOCUMENTO DE POLIZA

CREATE TABLE TB_PA_TIPO_DOC_POLIZA(
	id numeric(10) NOT NULL,
	tipo_documento varchar(100) NULL,
	fecha_creacion date NULL,
	descripcion varchar(100) NULL,
	estado varchar(20) NULL,
	plantilla varchar(200) NULL,
	tipo_plantilla varchar(20) NULL,
	plantilla_uno varchar(200) NULL,
	plantilla_dos varchar(200) NULL,
	plantilla_tres varchar(200) NULL,
	CONSTRAINT pk_documento PRIMARY KEY (id)
);
CREATE SEQUENCE AGRICOLA.SEQ_TIPO_DOCUMENTO INCREMENT BY 1 MINVALUE 0 NOCYCLE NOCACHE NOORDER ;


CREATE TABLE TB_PA_DOC_SOLICITUD_POLIZA (
	ID NUMERIC(10) NOT NULL,
	NOMBRE_ARCHIVO VARCHAR(150) NULL,
	ARCHIVO BLOB NULL,
	ESTADO VARCHAR(20) NULL,
	ID_TIPO_DOCUMENTO NUMERIC(10) NULL,
	FECHA_CREACION DATE NULL,
	FECHA_ACTUALIZACION DATE NULL,
	ID_SOLICITUD_POLIZA NUMERIC (10) NULL,
	CONSTRAINT PK_DOC_SOLICITUD_POL PRIMARY KEY (ID),
	CONSTRAINT UN_DOC_SOLICITUD_ID UNIQUE (ID_TIPO_DOCUMENTO, ID_SOLICITUD_POLIZA)
);
ALTER TABLE TB_PA_DOC_SOLICITUD_POLIZA ADD CONSTRAINT FK_SOL_POLIZA_ID FOREIGN KEY (ID_SOLICITUD_POLIZA) REFERENCES TB_PA_SOLICITUD_POLIZA(ID);
ALTER TABLE TB_PA_DOC_SOLICITUD_POLIZA ADD CONSTRAINT FK_CON_TIPO_DOC_ID FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TB_PA_TIPO_DOC_POLIZA(ID);
